tmdb-movies:
    component: "@sls-next/serverless-component@1.17.0"
    inputs:
        nextConfigDir: "./packages/movies"
        build:
            cwd: "./packages/movies"

tmdb-home:
    component: "@sls-next/serverless-component@1.17.0"
    inputs:
        domain: ["tmdb", "victorbarros.com"]
        nextConfigDir: "./packages/home"
        build:
            cwd: "./packages/home"
            env:
                MOVIES_URL: ${tmdb-movies.appUrl}
        cloudfront:
            origins:
                - url: ${tmdb-movies.appUrl}
                  pathPatterns:
                    /movies*:
                        minTTL: 0
                        maxTTL: 86400
                        defaultTTL: 86400

